---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aerofb-helloworld
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ckatsak/aerofb-helloworld:0.0.1
          ports:
            - containerPort: 8000
