---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aerofb-json_serdes
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ckatsak/aerofb-json_serdes:0.0.1
          ports:
            - containerPort: 8000
