---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aerofb-video_processing
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ckatsak/aerofb-video_processing:0.0.1
          ports:
            - containerPort: 8000
